# Builds a release.
name: Build Package

on:
  workflow_call:
    secrets:
      CF_API_KEY:
        required: true
      WAGO_API_TOKEN:
        required: true

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Run LuaCheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          config: https://raw.githubusercontent.com/Skullcan/shared/main/config/.luacheckrc

      - name: Run Packager
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
